const router = require('express').Router('../controllers/tickets')
const ticketsCTRL = require('../controllers/tickets')
router.get('/:ticketid', null)
router.post('/new', null)
router.delete('/:ticketid', null)
